### ISSUE TITLE
humility flash with pyocd doesn't say what is missing

### ISSUE THREAD

**Issue by rmustacc** [oxidecomputer/humility#185]
If you have some file missing for some reason while trying to use `humility flash` on the RoT, it's hard to know what it is that's actually missing because the error message doesn't say:

```
$ sudo ./target/release/humility -a ../hubris/target/gimlet-rot/dist/build-gimlet-rot.zip  flash
humility: attached via CMSIS-DAP
humility: specifying serial XAEPYT3E3JX0D
humility flash failed: failed to flash ("pyocd" "flash" "-t" "lpc55s28" "--format" "hex" "/tmp/.tmpmN8PJ1" "-u" "XAEPYT3E3JX0D")

Caused by:
    No such file or directory (os error 2)
```

It'd really help if it could tell us what actually caused an ENOENT.

**Comment by cbiffle** [comment]
Thanks for the backtrace!

The issue here is that executing a subprocess can fail in two separate ways:
- The subprocess runs but does not exit successfully. This is the case Humility is mostly expecting right now.
- The subprocess fails to run in the first place, because the program is not found, is not executable, is in the wrong format, etc etc. This is the case you're hitting.

The error reporting in the flash subcommand _does_ treat these two cases differently, but using nearly identical wording that is not at all obvious. I've pushed a proposed fix in #186. If you have the time I'd be curious to see if it improves your failure message (it should).
